CS_3010/Reference/w7code/w7code15/cars/config/routes.rb
Cars::Application.routes.draw do
  get "main/welcome"

  get "main/result"

  post "main/result"

  resources :corvettes











end

CS_3010/Reference/w7code/w7code15/cars/app/models/corvette.rb
class Corvette < ActiveRecord::Base
end

CS_3010/Reference/w7code/w7code15/cars/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

CS_3010/Reference/w7code/w7code15/cars/app/controllers/corvettes_controller.rb
class CorvettesController < ApplicationController
  # GET /corvettes
  # GET /corvettes.json
  def index
    @corvettes = Corvette.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @corvettes }
    end
  end

  # GET /corvettes/1
  # GET /corvettes/1.json
  def show
    @corvette = Corvette.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @corvette }
    end
  end

  # GET /corvettes/new
  # GET /corvettes/new.json
  def new
    @corvette = Corvette.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @corvette }
    end
  end

  # GET /corvettes/1/edit
  def edit
    @corvette = Corvette.find(params[:id])
  end

  # POST /corvettes
  # POST /corvettes.json
  def create
    @corvette = Corvette.new(params[:corvette])

    respond_to do |format|
      if @corvette.save
        format.html { redirect_to @corvette, notice: 'Corvette was successfully created.' }
        format.json { render json: @corvette, status: :created, location: @corvette }
      else
        format.html { render action: "new" }
        format.json { render json: @corvette.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /corvettes/1
  # PUT /corvettes/1.json
  def update
    @corvette = Corvette.find(params[:id])

    respond_to do |format|
      if @corvette.update_attributes(params[:corvette])
        format.html { redirect_to @corvette, notice: 'Corvette was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @corvette.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corvettes/1
  # DELETE /corvettes/1.json
  def destroy
    @corvette = Corvette.find(params[:id])
    @corvette.destroy

    respond_to do |format|
      format.html { redirect_to corvettes_url }
      format.json { head :ok }
    end
  end
end

CS_3010/Reference/w7code/w7code15/cars/app/controllers/main_controller.rb
class MainController < ApplicationController
# welcome method - fetches values for the initial view
  def welcome
    @num_cars = Corvette.count
  end

# result method - fetches values for the result view
  def result
    @year1 = params[:year1].to_i
    @year2 = params[:year2].to_i
    @body = params[:body]
    @selected_cars = Corvette.where(["year >= ? and year <= ? and
                     body_style = ?", @year1, @year2, @body]).all
  end

end

CS_3010/Reference/w7code/w7code15/cars/app/helpers/application_helper.rb
module ApplicationHelper
end

CS_3010/Reference/w7code/w7code15/cars/app/helpers/corvettes_helper.rb
module CorvettesHelper
end

CS_3010/Reference/w7code/w7code15/cars/app/helpers/main_helper.rb
module MainHelper
end

CS_3010/Reference/w7code/w7code15/cars/app/views/corvettes/_form.html.erb
<%= form_for(@corvette) do |f| %>
  <% if @corvette.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corvette.errors.count, "error") %> prohibited this corvette from being saved:</h2>

      <ul>
      <% @corvette.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body_style %><br />
    <%= f.text_field :body_style %>
  </div>
  <div class="field">
    <%= f.label :miles %><br />
    <%= f.text_field :miles %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

CS_3010/Reference/w7code/w7code15/cars/app/views/corvettes/edit.html.erb
<h1>Editing corvette</h1>

<%= render 'form' %>

<%= link_to 'Show', @corvette %> |
<%= link_to 'Back', corvettes_path %>

CS_3010/Reference/w7code/w7code15/cars/app/views/corvettes/index.html.erb
<h1>Listing corvettes</h1>

<table>
  <tr>
    <th>Body style</th>
    <th>Miles</th>
    <th>Year</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @corvettes.each do |corvette| %>
  <tr>
    <td><%= corvette.body_style %></td>
    <td><%= corvette.miles %></td>
    <td><%= corvette.year %></td>
    <td><%= corvette.state %></td>
    <td><%= link_to 'Show', corvette %></td>
    <td><%= link_to 'Edit', edit_corvette_path(corvette) %></td>
    <td><%= link_to 'Destroy', corvette, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Corvette', new_corvette_path %>

CS_3010/Reference/w7code/w7code15/cars/app/views/corvettes/new.html.erb
<h1>New corvette</h1>

<%= render 'form' %>

<%= link_to 'Back', corvettes_path %>

CS_3010/Reference/w7code/w7code15/cars/app/views/corvettes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body style:</b>
  <%= @corvette.body_style %>
</p>

<p>
  <b>Miles:</b>
  <%= @corvette.miles %>
</p>

<p>
  <b>Year:</b>
  <%= @corvette.year %>
</p>

<p>
  <b>State:</b>
  <%= @corvette.state %>
</p>


<%= link_to 'Edit', edit_corvette_path(@corvette) %> |
<%= link_to 'Back', corvettes_path %>

CS_3010/Reference/w7code/w7code15/cars/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cars</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

CS_3010/Reference/w7code/w7code15/cars/app/views/layouts/main.html.erb
<!DOCTYPE html>
<!-- main.html.erb - a layout for the main controller of cars
     -->
<html lang="en">
  <head> 
    <title> Main </title>
    <%= stylesheet_link_tag "mainstyles" %>
    <meta charset = "UTF-8" />
  </head>
  <body>
    <h1> Aidan's Used Car Lot </h1>
    <h2> Welcome to our home document </h2>
    <%= yield  %>
    <hr/>
    <p> Copyright 2012, AUCL, Inc. </p>
  </body>
        </html>

CS_3010/Reference/w7code/w7code15/cars/app/views/main/main.html.erb
<!DOCTYPE html>
<!-- main.html.erb - a layout for the main controller of cars
     -->
<html lang="en">
  <head> 
    <title> Main </title>
    <meta charset = "UTF-8" />
    <%= stylesheet_link_tag "mainstyles" %>
  </head>
  <body>
    <h1> Aidan's Used Car Lot </h1>
    <h2> Welcome to our home document </h2>
    <%= yield  %>
    <hr/>
    <p> Copyright 2012, AUCL, Inc. </p>
  </body>
        </html>

CS_3010/Reference/w7code/w7code15/cars/app/views/main/result.html.erb
<!-- result.html.erb - the result of the user request for
                       information about cars  
     -->
    <p>
<!-- Display what the user asked for -->
      Cars from <%= @year1 %> to <%= @year2 %>
       with the <%= @body %> body style 
    </p>
<!-- Display the results of the request in a table -->
    <table border = "border">
      <tr>
        <th> Body Style </th>
        <th> Miles </th>
        <th> Year </th>
      </tr>
<!-- Put the cars in @selected_cars in the table -->
      <% @selected_cars.each do |car| %>
        <tr>
          <td> <%= car.body_style %> </td>
          <td> <%= car.miles %> </td>
          <td> <%= car.year %> </td>
        </tr>
      <% end %> <!-- end of do loop -->
    </table>

CS_3010/Reference/w7code/w7code15/cars/app/views/main/welcome.html.erb
<!-- welcome.html.erb - initial view for the cars application
    -->
<!-- The initial information -->
<p>
 <!-- <h1> Aidan's Used Car Lot </h1>
  <h2> Welcome to our home document </h2> -->
  We currently have <%= @num_cars %> used Corvettes listed <br />
  To request information on available cars, please fill out <br />
  the following form and submit it 
</p>
<!-- The form to collect input from the user about their interests  
    -->
<form action = "result"  method = "post" >
  From year: <input type = "text"  size = "4"  name = "year1" /> 
  To year: <input type = "text"  size = "4"  name = "year2" /> 
  Body style: <input type = "text"  size = "12"  name = "body" />
  <br />
  <input  type = "submit"  value = "Submit request" /> <br />
  <input type = "reset"  value = "Reset form" /> <br />
    </form>